# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: supply_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supply_department
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  db_data:
